
INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H

.DATA
   SIZE EQU 2D
   BUFFER DB SIZE DUP ('X')
   
.CODE
   ENTRY:						; DO THE CHARACTER ENTRY
      PRINT 'ENTER A ASCII CHARACTER: '
      LEA DI, BUFFER
      MOV DX, SIZE
      CALL GET_STRING
      PUTC 13D
      PUTC 10D
      
      PRINT 'THE ASCII CODE OF THE CHARACTER ['
      MOV SI, DI
      CALL PRINT_STRING
      PRINT '] IN BINARY IS EQUIVALENT OF: '
      
      MOV AX, [DI]
      MOV AH, 10000000B			; MASK FOR A BINARY VALUE TEST
      MOV CX, 08H				; DEFINITION OF THE 8 BITS COUNTER
      WRITE_BIT:				; ROUTINE OF THE BINARY VALUE PRESENTATION
         TEST AL, AH			; VERIFY IF THE AL INTERRUPT DIDN'T HAVE BEEN MODIFIED
         JZ WRITE_0				; IF THE BIT TEST BE 0, WRITE IT AS 0
         PUTC '1'				; IF NOT, WRITE 1
         JMP NEXT_BIT			; GET THE NEXT BIT OF THE SEQUENCE
         WRITE_0:
            PUTC '0'			; WRITE ZERO
         NEXT_BIT:
         SHR AH, 01H			; MOVE ONE BIT FROM THE MASK TO THE RIGHT
      LOOP WRITE_BIT
      
      PUTC 13D
      PUTC 10D
      PRINT 'WANT TO FINISH THE EXECUTION (Y/N): '
      LEA DI, BUFFER
      MOV DX, SIZE
      CALL GET_STRING
      PUTC 13D
      PUTC 10D
      MOV AX, [DI]
      
      CMP AX, 079H				; IF THE CHARACTER ENTERED WAS 'Y'
      JE GET_CAPITAL			; CONVERT IT TO 'Y'
      JNE GET_NORMAL			; IF NOT, STAY THE ENTERED
      GET_CAPITAL:
         SUB AX, 020H
      GET_NORMAL:
      CMP AX, 059H				; IF THE ANSWER BE DIFFERENT THAN 'Y'
      JE EXIT					; EXIT THE PROGRAM
   JMP ENTRY					; IF NOT, ENTER THE NEXT CHARACTER
   EXIT:
      HLT
      
   DEFINE_GET_STRING
   DEFINE_PRINT_STRING
END